app = "discord-points-bot"
primary_region = "sjc"

[build]

[env]
  PORT = "5000"
  PYTHONUNBUFFERED = "1"

[http_services]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2

  [[http_services.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "10s"
    path = "/"

[processes]
  app = "python -u bot.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mount]
  source = "discord_bot_data"
  destination = "/data"
