app = "discord-point-tracker"
primary_region = "sjc"

[build]

[env]
  PORT = "5000"

[http_services]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_services.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/"

[processes]
  app = "python bot.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512